/*
 * Image Store
 *
 * Image store service provides Albums and Image management operaions
 *
 * API version: 1.0.0
 * Contact: diksha.may14@outlook.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"image-store-service/logger"
	"image-store-service/server"
	"sync"
	"time"
)

func main() {

	var wg sync.WaitGroup

	wg.Add(1)
	go func() {
		defer wg.Done()
		server.Start()
	}()
	time.Sleep(1 * time.Second)
	logger.Logger.Info("Server Started")

	wg.Wait()
}
