/*
 * Image Store
 *
 * Image store service provides Albums and Image management operaions
 *
 * API version: 1.0.0
 * Contact: diksha.may14@outlook.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
)

// AddAlbumApiRouter defines the required methods for binding the api requests to a responses for the AddAlbumApi
// The AddAlbumApiRouter implementation should parse necessary information from the http request,
// pass the data to a AddAlbumApiServicer to perform the required actions, then write the service results to the http response.
type AddAlbumApiRouter interface {
	AddAlbum(http.ResponseWriter, *http.Request)
}

// AddImageApiRouter defines the required methods for binding the api requests to a responses for the AddImageApi
// The AddImageApiRouter implementation should parse necessary information from the http request,
// pass the data to a AddImageApiServicer to perform the required actions, then write the service results to the http response.
type AddImageApiRouter interface {
	AddImage(http.ResponseWriter, *http.Request)
}

// DeleteAlbumApiRouter defines the required methods for binding the api requests to a responses for the DeleteAlbumApi
// The DeleteAlbumApiRouter implementation should parse necessary information from the http request,
// pass the data to a DeleteAlbumApiServicer to perform the required actions, then write the service results to the http response.
type DeleteAlbumApiRouter interface {
	DeleteAlbum(http.ResponseWriter, *http.Request)
}

// DeleteImageByIdApiRouter defines the required methods for binding the api requests to a responses for the DeleteImageByIdApi
// The DeleteImageByIdApiRouter implementation should parse necessary information from the http request,
// pass the data to a DeleteImageByIdApiServicer to perform the required actions, then write the service results to the http response.
type DeleteImageByIdApiRouter interface {
	DeleteImageById(http.ResponseWriter, *http.Request)
}

// DeleteImagesByAlbumApiRouter defines the required methods for binding the api requests to a responses for the DeleteImagesByAlbumApi
// The DeleteImagesByAlbumApiRouter implementation should parse necessary information from the http request,
// pass the data to a DeleteImagesByAlbumApiServicer to perform the required actions, then write the service results to the http response.
type DeleteImagesByAlbumApiRouter interface {
	DeleteImagesByAlbum(http.ResponseWriter, *http.Request)
}

// GetAlbumsApiRouter defines the required methods for binding the api requests to a responses for the GetAlbumsApi
// The GetAlbumsApiRouter implementation should parse necessary information from the http request,
// pass the data to a GetAlbumsApiServicer to perform the required actions, then write the service results to the http response.
type GetAlbumsApiRouter interface {
	GetAlbums(http.ResponseWriter, *http.Request)
}

// GetImageByIdApiRouter defines the required methods for binding the api requests to a responses for the GetImageByIdApi
// The GetImageByIdApiRouter implementation should parse necessary information from the http request,
// pass the data to a GetImageByIdApiServicer to perform the required actions, then write the service results to the http response.
type GetImageByIdApiRouter interface {
	GetImageById(http.ResponseWriter, *http.Request)
}

// GetImagesByAlbumApiRouter defines the required methods for binding the api requests to a responses for the GetImagesByAlbumApi
// The GetImagesByAlbumApiRouter implementation should parse necessary information from the http request,
// pass the data to a GetImagesByAlbumApiServicer to perform the required actions, then write the service results to the http response.
type GetImagesByAlbumApiRouter interface {
	GetImagesByAlbum(http.ResponseWriter, *http.Request)
}

// AddAlbumApiServicer defines the api actions for the AddAlbumApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type AddAlbumApiServicer interface {
	AddAlbum(AddAlbumRequest) (interface{}, error)
}

// AddImageApiServicer defines the api actions for the AddImageApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type AddImageApiServicer interface {
	AddImage(string, AddImageRequest) (interface{}, error)
}

// DeleteAlbumApiServicer defines the api actions for the DeleteAlbumApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DeleteAlbumApiServicer interface {
	DeleteAlbum(string) (interface{}, error)
}

// DeleteImageByIdApiServicer defines the api actions for the DeleteImageByIdApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DeleteImageByIdApiServicer interface {
	DeleteImageById(string) (interface{}, error)
}

// DeleteImagesByAlbumApiServicer defines the api actions for the DeleteImagesByAlbumApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DeleteImagesByAlbumApiServicer interface {
	DeleteImagesByAlbum(string) (interface{}, error)
}

// GetAlbumsApiServicer defines the api actions for the GetAlbumsApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type GetAlbumsApiServicer interface {
	GetAlbums() (interface{}, error)
}

// GetImageByIdApiServicer defines the api actions for the GetImageByIdApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type GetImageByIdApiServicer interface {
	GetImageById(string) (interface{}, error)
}

// GetImagesByAlbumApiServicer defines the api actions for the GetImagesByAlbumApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type GetImagesByAlbumApiServicer interface {
	GetImagesByAlbum(string) (interface{}, error)
}
