/*
 * Image Store
 *
 * Image store service provides Albums and Image management operaions
 *
 * API version: 1.0.0
 * Contact: diksha.may14@outlook.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"image-store-service/constants"
	"image-store-service/logger"
	"image-store-service/service"
)

// AddAlbumApiService is a service that implents the logic for the AddAlbumApiServicer
// This service should implement the business logic for every endpoint for the AddAlbumApi API.
// Include any external packages or services that will be required by this service.
type AddAlbumApiService struct {
}

// NewAddAlbumApiService creates a default api service
func NewAddAlbumApiService() AddAlbumApiServicer {
	return &AddAlbumApiService{}
}

// AddAlbum - Create an album
func (s *AddAlbumApiService) AddAlbum(addAlbumRequest AddAlbumRequest) (interface{}, error) {
	logger.Logger.Trace(constants.LogBeginFunc)
	jsonString, err := json.Marshal(&addAlbumRequest)

	err = service.AddAlbum(string(jsonString))
	if err != nil {
		logger.Logger.Error(err.Error(), err)
		return nil, err
	} else {
		logger.Logger.Trace(constants.LogFinishFunc)
		return nil, nil
	}
}
