/*
 * Image Store
 *
 * Image store service provides Albums and Image management operaions
 *
 * API version: 1.0.0
 * Contact: diksha.may14@outlook.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"image-store-service/constants"
	"image-store-service/logger"
	"image-store-service/service"
)

// AddImageApiService is a service that implents the logic for the AddImageApiServicer
// This service should implement the business logic for every endpoint for the AddImageApi API.
// Include any external packages or services that will be required by this service.
type AddImageApiService struct {
}

// NewAddImageApiService creates a default api service
func NewAddImageApiService() AddImageApiServicer {
	return &AddImageApiService{}
}

// AddImage - Add an image in an album with the the given id
func (s *AddImageApiService) AddImage(id string, addImageRequest AddImageRequest) (interface{}, error) {
	logger.Logger.Trace(constants.LogBeginFunc)
	jsonString, err := json.Marshal(&addImageRequest)

	err = service.AddImage(id, string(jsonString))
	if err != nil {
		logger.Logger.Error(err.Error(), err)
		return nil, err
	} else {
		logger.Logger.Trace(constants.LogFinishFunc)
		return nil, nil
	}
}
