/*
 * Image Store
 *
 * Image store service provides Albums and Image management operaions
 *
 * API version: 1.0.0
 * Contact: diksha.may14@outlook.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"image-store-service/constants"
	"image-store-service/logger"
	"image-store-service/service"
)

// DeleteAlbumApiService is a service that implents the logic for the DeleteAlbumApiServicer
// This service should implement the business logic for every endpoint for the DeleteAlbumApi API.
// Include any external packages or services that will be required by this service.
type DeleteAlbumApiService struct {
}

// NewDeleteAlbumApiService creates a default api service
func NewDeleteAlbumApiService() DeleteAlbumApiServicer {
	return &DeleteAlbumApiService{}
}

// DeleteAlbum - delete an album with the the given id
func (s *DeleteAlbumApiService) DeleteAlbum(id string) (interface{}, error) {
	logger.Logger.Trace(constants.LogBeginFunc)
	err := service.DeleteAlbumById(id)
	if err != nil {
		logger.Logger.Error(err.Error(), err)
		return nil, err
	} else {
		logger.Logger.Trace(constants.LogFinishFunc)
		return nil, nil
	}
}
