/*
 * Image Store
 *
 * Image store service provides Albums and Image management operaions
 *
 * API version: 1.0.0
 * Contact: diksha.may14@outlook.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	_ "github.com/gorilla/mux"
	"image-store-service/logger"
	"net/http"
)

// A AddAlbumApiController binds http requests to an api service and writes the service results to the http response
type AddAlbumApiController struct {
	service AddAlbumApiServicer
}

// NewAddAlbumApiController creates a default api controller
func NewAddAlbumApiController(s AddAlbumApiServicer) Router {
	return &AddAlbumApiController{service: s}
}

// Routes returns all of the api route for the AddAlbumApiController
func (c *AddAlbumApiController) Routes() Routes {
	return Routes{
		{
			"AddAlbum",
			http.MethodPost,
			"/albums",
			c.AddAlbum,
		},
	}
}

// AddAlbum - Create an album
func (c *AddAlbumApiController) AddAlbum(w http.ResponseWriter, r *http.Request) {
	addAlbumRequest := &AddAlbumRequest{}
	if err := json.NewDecoder(r.Body).Decode(&addAlbumRequest); err != nil {
		logger.Logger.Error(err)
		w.WriteHeader(http.StatusBadRequest)
		return
	}

	result, err := c.service.AddAlbum(*addAlbumRequest)
	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		return
	}

	EncodeJSONResponse(result, http.StatusOK, w)
}
