/*
 * Image Store
 *
 * Image store service provides Albums and Image management operaions
 *
 * API version: 1.0.0
 * Contact: diksha.may14@outlook.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"image-store-service/constants"
	"image-store-service/logger"
	"image-store-service/service"
)

// GetImagesByAlbumApiService is a service that implents the logic for the GetImagesByAlbumApiServicer
// This service should implement the business logic for every endpoint for the GetImagesByAlbumApi API.
// Include any external packages or services that will be required by this service.
type GetImagesByAlbumApiService struct {
}

// NewGetImagesByAlbumApiService creates a default api service
func NewGetImagesByAlbumApiService() GetImagesByAlbumApiServicer {
	return &GetImagesByAlbumApiService{}
}

// GetImagesByAlbum - Get all the images associated with an album of a given id
func (s *GetImagesByAlbumApiService) GetImagesByAlbum(id string) (interface{}, error) {
	logger.Logger.Trace(constants.LogBeginFunc)
	result, err := service.ListImagesByAlbumID(id)
	if err != nil {
		logger.Logger.Error(err.Error(), err)
		return nil, err
	} else {
		logger.Logger.Trace(constants.LogFinishFunc)
		return result, nil
	}
}
