/*
 * Image Store
 *
 * Image store service provides Albums and Image management operaions
 *
 * API version: 1.0.0
 * Contact: diksha.may14@outlook.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"image-store-service/constants"
	"image-store-service/logger"
	"image-store-service/service"
)

// GetImageByIdApiService is a service that implents the logic for the GetImageByIdApiServicer
// This service should implement the business logic for every endpoint for the GetImageByIdApi API.
// Include any external packages or services that will be required by this service.
type GetImageByIdApiService struct {
}

// NewGetImageByIdApiService creates a default api service
func NewGetImageByIdApiService() GetImageByIdApiServicer {
	return &GetImageByIdApiService{}
}

// GetImageById - Get an image with the given image id
func (s *GetImageByIdApiService) GetImageById(id string) (interface{}, error) {
	logger.Logger.Trace(constants.LogBeginFunc)
	result, err := service.GetImageByID(id)
	if err != nil {
		logger.Logger.Error(err.Error(), err)
		return nil, err
	} else {
		logger.Logger.Trace(constants.LogFinishFunc)
		return result, nil
	}
}
