/*
 * Image Store
 *
 * Image store service provides Albums and Image management operaions
 *
 * API version: 1.0.0
 * Contact: diksha.may14@outlook.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"image-store-service/constants"
	"image-store-service/logger"
	"image-store-service/service"
)

// GetAlbumsApiService is a service that implents the logic for the GetAlbumsApiServicer
// This service should implement the business logic for every endpoint for the GetAlbumsApi API.
// Include any external packages or services that will be required by this service.
type GetAlbumsApiService struct {
}

// NewGetAlbumsApiService creates a default api service
func NewGetAlbumsApiService() GetAlbumsApiServicer {
	return &GetAlbumsApiService{}
}

// GetAlbums - Get all albums
func (s *GetAlbumsApiService) GetAlbums() (interface{}, error) {
	logger.Logger.Trace(constants.LogBeginFunc)
	result, err := service.ListAlbums()
	if err != nil {
		logger.Logger.Error(err.Error(), err)
		return nil, err
	} else {
		logger.Logger.Trace(constants.LogFinishFunc)
		return result, nil
	}
}
