/*
 * Image Store
 *
 * Image store service provides Albums and Image management operaions
 *
 * API version: 1.0.0
 * Contact: diksha.may14@outlook.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"image-store-service/constants"
	"image-store-service/logger"
	"image-store-service/service"
)

// DeleteImagesByAlbumApiService is a service that implents the logic for the DeleteImagesByAlbumApiServicer
// This service should implement the business logic for every endpoint for the DeleteImagesByAlbumApi API.
// Include any external packages or services that will be required by this service.
type DeleteImagesByAlbumApiService struct {
}

// NewDeleteImagesByAlbumApiService creates a default api service
func NewDeleteImagesByAlbumApiService() DeleteImagesByAlbumApiServicer {
	return &DeleteImagesByAlbumApiService{}
}

// DeleteImagesByAlbum - delete all images in an album with the the given id
func (s *DeleteImagesByAlbumApiService) DeleteImagesByAlbum(id string) (interface{}, error) {
	logger.Logger.Trace(constants.LogBeginFunc)
	err := service.DeleteImagesByAlbum(id)
	if err != nil {
		logger.Logger.Error(err.Error(), err)
		return nil, err
	} else {
		logger.Logger.Trace(constants.LogFinishFunc)
		return nil, nil
	}
}
