/*
 * Image Store
 *
 * Image store service provides Albums and Image management operaions
 *
 * API version: 1.0.0
 * Contact: diksha.may14@outlook.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"image-store-service/constants"
	"image-store-service/logger"
	"image-store-service/service"
)

// DeleteImageByIdApiService is a service that implents the logic for the DeleteImageByIdApiServicer
// This service should implement the business logic for every endpoint for the DeleteImageByIdApi API.
// Include any external packages or services that will be required by this service.
type DeleteImageByIdApiService struct {
}

// NewDeleteImageByIdApiService creates a default api service
func NewDeleteImageByIdApiService() DeleteImageByIdApiServicer {
	return &DeleteImageByIdApiService{}
}

// DeleteImageById - delete an image with the the given image id
func (s *DeleteImageByIdApiService) DeleteImageById(id string) (interface{}, error) {
	logger.Logger.Trace(constants.LogBeginFunc)
	err := service.DeleteImageById(id)
	if err != nil {
		logger.Logger.Error(err.Error(), err)
		return nil, err
	} else {
		logger.Logger.Trace(constants.LogFinishFunc)
		return nil, nil
	}
}
